version: "3.9"

services:
  api:
    container_name: chatapp_api
    build:
      context: .
      dockerfile: ./dockerfiles/ChatApp.API/Dockerfile
    env_file:
      - ./.env
    ports:
      - "5000:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - chatapp_network

  client:
    container_name: chatapp_client
    build:
      context: ./ChatApp.Client
      dockerfile: ../dockerfiles/ChatApp.Client/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - chatapp_network

  postgres:
    container_name: chatapp_postgres
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ChatDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatapp_network

  redis:
    container_name: chatapp_redis
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    networks:
      - chatapp_network

volumes:
  postgres_data:

networks:
  chatapp_network:
