name: Build and Push ChatApp Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Login to Docker Hub using official action
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ------------------------------
      # Build API image
      # ------------------------------
      - name: Build API image
        run: |
          docker build \
            -f src/dockerfiles/ChatApp.API/Dockerfile \
            -t umarbek/chatapp-api:latest \
            -t umarbek/chatapp-api:${{ github.sha }} \
            src

      # ------------------------------
      # Build Client image
      # ------------------------------
      - name: Build Client image
        run: |
          docker build \
            -f src/dockerfiles/ChatApp.Client/Dockerfile \
            -t umarbek/chatapp-client:latest \
            -t umarbek/chatapp-client:${{ github.sha }} \
            src/ChatApp.Client

      # ------------------------------
      # Push Images
      # ------------------------------
      - name: Push API image
        run: |
          docker push umarbek/chatapp-api:latest
          docker push umarbek/chatapp-api:${{ github.sha }}

      - name: Push Client image
        run: |
          docker push umarbek/chatapp-client:latest
          docker push umarbek/chatapp-client:${{ github.sha }}
